### 1) Успешный запрос кода (новый номер) → ожидаем 200
POST http://localhost:8337/api/request-code
Content-Type: application/json

{
  "phone": "+79999990001"
}


### 2) Повторный запрос кода (меньше 1 минуты, должен вернуть старый код) → ожидаем 200
POST http://localhost:8337/api/request-code
Content-Type: application/json

{
  "phone": "+79999990001"
}


### 3) Превышен лимит (предположим, сделали 3 запроса за 15 мин) → ожидаем 429
POST http://localhost:8337/api/request-code
Content-Type: application/json

{
  "phone": "+79999990001"
}


### 4) Некорректный номер (короткий) → ожидаем 400
POST http://localhost:8337/api/request-code
Content-Type: application/json

{
  "phone": "123"
}


### 5) Успешная верификация (новый пользователь ⇒ 201)
POST http://localhost:8337/api/verify-code
Content-Type: application/json

{
  "phone": "+79999990001",
  "code": "2134"
}


### 6) Успешная верификация (существующий пользователь ⇒ 200)
POST http://localhost:8337/api/verify-code
Content-Type: application/json

{
  "phone": "+79999990001",
  "code": "1234"
}


### 7) Неверный код / просроченный ⇒ 400
POST http://localhost:8337/api/verify-code
Content-Type: application/json

{
  "phone": "+79999990001",
  "code": "0000"
}


### 8) Пропущены поля (нет code) ⇒ 400
POST http://localhost:8337/api/verify-code
Content-Type: application/json

{
  "phone": "+79999990001"
}
